int _putchar (char c);
void print_alphabet_x10(void);
void print_alphabet(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int);
void jack_bauer(void);
int _abs(int);
int print_last_digit(int c);
int add(int i, int a);
void print_to_98(int n);
void times_table(void);
